# Generated by Django 2.2.10 on 2020-04-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_documento_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(help_text='Escolha o arquivo para upload', upload_to='documentos'),
        ),
    ]
