# Generated by Django 2.2.10 on 2020-04-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0002_registrohoraextra_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='horas',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Informe a quantidade de horas extras', max_digits=5),
            preserve_default=False,
        ),
    ]
